#!/usr/bin/env ruby
#^syntax detection

site "https://supermarket.getchef.com/api/v1"

cookbook "apt", "2.9.2"
cookbook "build-essential", "2.2.4"
cookbook "git", "4.3.5"
cookbook "ruby_rbenv", "1.0.1"
cookbook "ruby_build", "0.8.0"
cookbook "vim", "2.0.0"
