#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

cookbook "apt",
  :version => "1.7.0"
cookbook "build-essential"
cookbook "git"
cookbook "rbenv",
  :git => "https://github.com/fnichol/chef-rbenv.git",
  :ref => "v0.7.2"
cookbook "ruby_build"
cookbook "vim"
